# Generated by Django 3.0.2 on 2020-02-12 08:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ongoing',
        ),
        migrations.AddField(
            model_name='profile',
            name='fb_messenger',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Complete', 'Complete'), ('Inactive', 'Inactive')], default='Ongoing', max_length=10, null=True, verbose_name='Project status?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, null=True)),
                ('worked_at', models.CharField(max_length=128, null=True)),
                ('duration', models.DurationField(default=datetime.timedelta(days=30))),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='userprofile.Profile')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experience',
            },
        ),
    ]
